### ISSUE TITLE
Wrong variable name to locate libgcrypt

### ISSUE THREAD

**Issue by grandkarabas** [Lekensteyn/luagcrypt#2]
When I run this:

`luarocks make luagcrypt-0.2-1.rockspec`

I got the following:

`Error: Could not find expected file libgcrypt-20.lib, or libgcrypt-20.dll, or liblibgcrypt-20.dll for LIBGCRYPT -- you may have to install LIBGCRYPT in your system and/or set the LIBGCRYPT_DIR variable`

But this is not quite right: actually I have to set a variable named LIBGCRYPT_**LIB**DIR. Same thing to locate gcrypt.h: I have to set a variable named LIBGCRYPT_**INC**DIR, not the LIBGCRYPT_DIR.

**Comment by Lekensteyn** [comment]
What luarocks version are you using? At least with luarocks 2.3.0, when `LIBGCRYPT_INCDIR`, `LIBGCRYPT_BINDIR` or `LIBGCRYPT_LIBDIR` are not set, it will be initialized with `LIBGCRYPT_DIR` **concatenated** with `/include`, `/bin` or `/lib`. When you put everything in a single directory, then you have to set the individual directories.

If you always have all dependencies in a single directory instead of the usual lib, bin and include subdirs, consider changing [external_deps_subdirs](https://github.com/keplerproject/luarocks/wiki/Config-file-format) in your site-local configuration file.

So, use `LIBGCRYPT_DIR=C:\gcrypt` if you have a directory `C:\gcrypt` with this layout (which is what is currently used in the integration tests):

```
include\gcrypt.h
include\libgpg-error.h
lib\libgcrypt-20.dll
lib\libgcrypt-20.lib
lib\libgpg-error...
```

Use `LIBGCRYPT_INCDIR=C:\gcrypt LIBGCRYPT_LIBDIR=C:\gcrypt` if there are no subdirectories:

```
gcrypt.h
libgpg-error.h
libgcrypt-20.dll
libgcrypt-20.lib
libgpg-error...
```

**Comment by grandkarabas** [comment]
You are absolutely right , I am using too old version luarocks 2.0.2, thanks a lot

**Comment by Lekensteyn** [comment]
You're welcome, let me know if there are other issues.
